- hosts: all
  tasks:
    - name: Atualizar todos os pacotes do sistema
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Limpar pacotes obsoletos
      ansible.builtin.shell: |        
        dnf clean all -y
        exit 0
      register: shell_output  
      args:
        executable: /usr/bin/bash        
    - debug: var=shell_output